name: Prompt Harness

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  harness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          pip install -r requirements.txt pytest
      - name: Run prompt harness tests
        run: pytest tests/test_prompt_harness.py -q
