name: Remote Health Check

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    env:
      BACKEND_URL: https://ai-debug-copilot.onrender.com
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install requests pytest
      - name: Run remote health test
        run: pytest tests/test_remote.py -q
